# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/ui/motor/bumblebeeModuleTester.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setEnabled(True)
        self.logo.setGeometry(QtCore.QRect(20, 11, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(0, 71))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("/root/ui/motor/../resource/new_bumbkebee.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(830, 330, 151, 107))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.verticalLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButton_cw_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_cw_2.setFont(font)
        self.pushButton_cw_2.setObjectName("pushButton_cw_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_cw_2)
        self.pushButton_home_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_home_2.setFont(font)
        self.pushButton_home_2.setObjectName("pushButton_home_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_home_2)
        self.pushButton_ccw_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_ccw_2.setFont(font)
        self.pushButton_ccw_2.setObjectName("pushButton_ccw_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_ccw_2)
        self.lineEdit_pot_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_pot_2.setFont(font)
        self.lineEdit_pot_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pot_2.setObjectName("lineEdit_pot_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pot_2)
        self.lineEdit_home_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_home_2.setFont(font)
        self.lineEdit_home_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_home_2.setObjectName("lineEdit_home_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_home_2)
        self.lineEdit_not_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_not_2.setFont(font)
        self.lineEdit_not_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_not_2.setObjectName("lineEdit_not_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_not_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(960, 130, 151, 107))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.verticalLayoutWidget_2.setFont(font)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.formLayout = QtWidgets.QFormLayout(self.verticalLayoutWidget_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_cw_1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_cw_1.setFont(font)
        self.pushButton_cw_1.setObjectName("pushButton_cw_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_cw_1)
        self.pushButton_home_1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_home_1.setFont(font)
        self.pushButton_home_1.setObjectName("pushButton_home_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_home_1)
        self.pushButton_ccw_1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_ccw_1.setFont(font)
        self.pushButton_ccw_1.setObjectName("pushButton_ccw_1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_ccw_1)
        self.lineEdit_pot_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_pot_1.setFont(font)
        self.lineEdit_pot_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pot_1.setObjectName("lineEdit_pot_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pot_1)
        self.lineEdit_home_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_home_1.setFont(font)
        self.lineEdit_home_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_home_1.setObjectName("lineEdit_home_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_home_1)
        self.lineEdit_not_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_not_1.setFont(font)
        self.lineEdit_not_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_not_1.setObjectName("lineEdit_not_1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_not_1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(640, 130, 151, 107))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.horizontalLayoutWidget.setFont(font)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.horizontalLayoutWidget)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.pushButton_cw_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_cw_3.setFont(font)
        self.pushButton_cw_3.setObjectName("pushButton_cw_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_cw_3)
        self.lineEdit_pot_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_pot_3.setFont(font)
        self.lineEdit_pot_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pot_3.setObjectName("lineEdit_pot_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pot_3)
        self.pushButton_home_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_home_3.setFont(font)
        self.pushButton_home_3.setObjectName("pushButton_home_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_home_3)
        self.lineEdit_home_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_home_3.setFont(font)
        self.lineEdit_home_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_home_3.setObjectName("lineEdit_home_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_home_3)
        self.pushButton_ccw_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_ccw_3.setFont(font)
        self.pushButton_ccw_3.setObjectName("pushButton_ccw_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_ccw_3)
        self.lineEdit_not_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_not_3.setFont(font)
        self.lineEdit_not_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_not_3.setObjectName("lineEdit_not_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_not_3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(50, 130, 151, 107))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.verticalLayoutWidget_3.setFont(font)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.formLayout_9 = QtWidgets.QFormLayout(self.verticalLayoutWidget_3)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.pushButton_cw_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_cw_9.setFont(font)
        self.pushButton_cw_9.setObjectName("pushButton_cw_9")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_cw_9)
        self.pushButton_home_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_home_9.setFont(font)
        self.pushButton_home_9.setObjectName("pushButton_home_9")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_home_9)
        self.pushButton_ccw_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_ccw_9.setFont(font)
        self.pushButton_ccw_9.setObjectName("pushButton_ccw_9")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_ccw_9)
        self.lineEdit_pot_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_pot_9.setFont(font)
        self.lineEdit_pot_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pot_9.setObjectName("lineEdit_pot_9")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pot_9)
        self.lineEdit_home_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_home_9.setFont(font)
        self.lineEdit_home_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_home_9.setObjectName("lineEdit_home_9")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_home_9)
        self.lineEdit_not_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_not_9.setFont(font)
        self.lineEdit_not_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_not_9.setObjectName("lineEdit_not_9")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_not_9)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(310, 530, 151, 107))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.verticalLayoutWidget_4.setFont(font)
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.formLayout_8 = QtWidgets.QFormLayout(self.verticalLayoutWidget_4)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.pushButton_cw_8 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_cw_8.setFont(font)
        self.pushButton_cw_8.setObjectName("pushButton_cw_8")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_cw_8)
        self.pushButton_home_8 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_home_8.setFont(font)
        self.pushButton_home_8.setObjectName("pushButton_home_8")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_home_8)
        self.pushButton_ccw_8 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_ccw_8.setFont(font)
        self.pushButton_ccw_8.setObjectName("pushButton_ccw_8")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_ccw_8)
        self.lineEdit_pot_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_pot_8.setFont(font)
        self.lineEdit_pot_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pot_8.setObjectName("lineEdit_pot_8")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pot_8)
        self.lineEdit_home_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_home_8.setFont(font)
        self.lineEdit_home_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_home_8.setObjectName("lineEdit_home_8")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_home_8)
        self.lineEdit_not_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_not_8.setFont(font)
        self.lineEdit_not_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_not_8.setObjectName("lineEdit_not_8")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_not_8)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(310, 130, 151, 107))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.verticalLayoutWidget_5.setFont(font)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.formLayout_6 = QtWidgets.QFormLayout(self.verticalLayoutWidget_5)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.pushButton_cw_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_cw_6.setFont(font)
        self.pushButton_cw_6.setObjectName("pushButton_cw_6")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_cw_6)
        self.pushButton_home_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_home_6.setFont(font)
        self.pushButton_home_6.setObjectName("pushButton_home_6")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_home_6)
        self.pushButton_ccw_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_ccw_6.setFont(font)
        self.pushButton_ccw_6.setObjectName("pushButton_ccw_6")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_ccw_6)
        self.lineEdit_pot_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_pot_6.setFont(font)
        self.lineEdit_pot_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pot_6.setObjectName("lineEdit_pot_6")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pot_6)
        self.lineEdit_home_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_home_6.setFont(font)
        self.lineEdit_home_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_home_6.setObjectName("lineEdit_home_6")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_home_6)
        self.lineEdit_not_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_not_6.setFont(font)
        self.lineEdit_not_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_not_6.setObjectName("lineEdit_not_6")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_not_6)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(640, 530, 151, 107))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.verticalLayoutWidget_6.setFont(font)
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.formLayout_5 = QtWidgets.QFormLayout(self.verticalLayoutWidget_6)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.pushButton_cw_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_cw_5.setFont(font)
        self.pushButton_cw_5.setObjectName("pushButton_cw_5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_cw_5)
        self.pushButton_home_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_home_5.setFont(font)
        self.pushButton_home_5.setObjectName("pushButton_home_5")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_home_5)
        self.pushButton_ccw_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_ccw_5.setFont(font)
        self.pushButton_ccw_5.setObjectName("pushButton_ccw_5")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_ccw_5)
        self.lineEdit_pot_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_pot_5.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_pot_5.setFont(font)
        self.lineEdit_pot_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pot_5.setObjectName("lineEdit_pot_5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pot_5)
        self.lineEdit_home_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_home_5.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_home_5.setFont(font)
        self.lineEdit_home_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_home_5.setObjectName("lineEdit_home_5")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_home_5)
        self.lineEdit_not_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_not_5.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_not_5.setFont(font)
        self.lineEdit_not_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_not_5.setObjectName("lineEdit_not_5")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_not_5)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(310, 330, 151, 107))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.verticalLayoutWidget_7.setFont(font)
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.verticalLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.pushButton_cw_7 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_cw_7.setFont(font)
        self.pushButton_cw_7.setObjectName("pushButton_cw_7")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_cw_7)
        self.pushButton_home_7 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_home_7.setFont(font)
        self.pushButton_home_7.setObjectName("pushButton_home_7")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_home_7)
        self.pushButton_ccw_7 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_ccw_7.setFont(font)
        self.pushButton_ccw_7.setObjectName("pushButton_ccw_7")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_ccw_7)
        self.lineEdit_home_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_home_7.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_home_7.setFont(font)
        self.lineEdit_home_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_home_7.setObjectName("lineEdit_home_7")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_home_7)
        self.lineEdit_not_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_not_7.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_not_7.setFont(font)
        self.lineEdit_not_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_not_7.setObjectName("lineEdit_not_7")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_not_7)
        self.lineEdit_pot_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_pot_7.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_pot_7.setFont(font)
        self.lineEdit_pot_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pot_7.setObjectName("lineEdit_pot_7")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pot_7)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(960, 530, 151, 107))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.verticalLayoutWidget_8.setFont(font)
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.formLayout_4 = QtWidgets.QFormLayout(self.verticalLayoutWidget_8)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.pushButton_cw_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_cw_4.setFont(font)
        self.pushButton_cw_4.setObjectName("pushButton_cw_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_cw_4)
        self.pushButton_home_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_home_4.setFont(font)
        self.pushButton_home_4.setObjectName("pushButton_home_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_home_4)
        self.pushButton_ccw_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.pushButton_ccw_4.setFont(font)
        self.pushButton_ccw_4.setObjectName("pushButton_ccw_4")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_ccw_4)
        self.lineEdit_pot_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_pot_4.setFont(font)
        self.lineEdit_pot_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pot_4.setObjectName("lineEdit_pot_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pot_4)
        self.lineEdit_home_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_home_4.setFont(font)
        self.lineEdit_home_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_home_4.setObjectName("lineEdit_home_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_home_4)
        self.lineEdit_not_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.lineEdit_not_4.setFont(font)
        self.lineEdit_not_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_not_4.setObjectName("lineEdit_not_4")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_not_4)
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(960, 110, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(640, 110, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(830, 310, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(960, 510, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(640, 510, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 110, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 310, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(310, 510, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 110, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 660, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(36)
        font.setItalic(True)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.Slider_9 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_9.setGeometry(QtCore.QRect(230, 130, 61, 541))
        self.Slider_9.setSingleStep(5)
        self.Slider_9.setPageStep(25)
        self.Slider_9.setSliderPosition(0)
        self.Slider_9.setTracking(True)
        self.Slider_9.setOrientation(QtCore.Qt.Vertical)
        self.Slider_9.setInvertedAppearance(True)
        self.Slider_9.setInvertedControls(False)
        self.Slider_9.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_9.setTickInterval(10)
        self.Slider_9.setObjectName("Slider_9")
        self.label_motor_value_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_motor_value_4.setGeometry(QtCore.QRect(970, 640, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_motor_value_4.setFont(font)
        self.label_motor_value_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor_value_4.setObjectName("label_motor_value_4")
        self.Slider_1 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_1.setGeometry(QtCore.QRect(960, 250, 300, 30))
        self.Slider_1.setSliderPosition(0)
        self.Slider_1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_1.setObjectName("Slider_1")
        self.Slider_2 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_2.setGeometry(QtCore.QRect(640, 450, 621, 31))
        self.Slider_2.setSliderPosition(0)
        self.Slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_2.setObjectName("Slider_2")
        self.Slider_3 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_3.setGeometry(QtCore.QRect(640, 250, 301, 29))
        self.Slider_3.setSliderPosition(0)
        self.Slider_3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_3.setObjectName("Slider_3")
        self.Slider_6 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_6.setGeometry(QtCore.QRect(500, 129, 20, 151))
        self.Slider_6.setOrientation(QtCore.Qt.Vertical)
        self.Slider_6.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_6.setObjectName("Slider_6")
        self.Slider_7 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_7.setGeometry(QtCore.QRect(500, 319, 20, 141))
        self.Slider_7.setOrientation(QtCore.Qt.Vertical)
        self.Slider_7.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Slider_7.setObjectName("Slider_7")
        self.Wheel_5 = QtWidgets.QLabel(self.centralwidget)
        self.Wheel_5.setEnabled(True)
        self.Wheel_5.setGeometry(QtCore.QRect(810, 530, 128, 128))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wheel_5.sizePolicy().hasHeightForWidth())
        self.Wheel_5.setSizePolicy(sizePolicy)
        self.Wheel_5.setMinimumSize(QtCore.QSize(0, 71))
        self.Wheel_5.setText("")
        self.Wheel_5.setPixmap(QtGui.QPixmap("/root/ui/motor/../resource/wheel.png"))
        self.Wheel_5.setScaledContents(True)
        self.Wheel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Wheel_5.setObjectName("Wheel_5")
        self.Wheel_8 = QtWidgets.QLabel(self.centralwidget)
        self.Wheel_8.setEnabled(True)
        self.Wheel_8.setGeometry(QtCore.QRect(480, 530, 128, 128))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wheel_8.sizePolicy().hasHeightForWidth())
        self.Wheel_8.setSizePolicy(sizePolicy)
        self.Wheel_8.setMinimumSize(QtCore.QSize(0, 71))
        self.Wheel_8.setText("")
        self.Wheel_8.setTextFormat(QtCore.Qt.AutoText)
        self.Wheel_8.setPixmap(QtGui.QPixmap("/root/ui/motor/../resource/wheel.png"))
        self.Wheel_8.setScaledContents(True)
        self.Wheel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.Wheel_8.setWordWrap(False)
        self.Wheel_8.setObjectName("Wheel_8")
        self.Wheel_4 = QtWidgets.QLabel(self.centralwidget)
        self.Wheel_4.setEnabled(True)
        self.Wheel_4.setGeometry(QtCore.QRect(1130, 530, 128, 128))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wheel_4.sizePolicy().hasHeightForWidth())
        self.Wheel_4.setSizePolicy(sizePolicy)
        self.Wheel_4.setMinimumSize(QtCore.QSize(0, 71))
        self.Wheel_4.setText("")
        self.Wheel_4.setPixmap(QtGui.QPixmap("/root/ui/motor/../resource/wheel.png"))
        self.Wheel_4.setScaledContents(True)
        self.Wheel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Wheel_4.setObjectName("Wheel_4")
        self.label_motor_value_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_motor_value_6.setGeometry(QtCore.QRect(320, 240, 130, 41))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_motor_value_6.setFont(font)
        self.label_motor_value_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor_value_6.setObjectName("label_motor_value_6")
        self.label_motor_value_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_motor_value_5.setGeometry(QtCore.QRect(650, 640, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_motor_value_5.setFont(font)
        self.label_motor_value_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor_value_5.setObjectName("label_motor_value_5")
        self.label_motor_value_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_motor_value_7.setGeometry(QtCore.QRect(320, 440, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_motor_value_7.setFont(font)
        self.label_motor_value_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor_value_7.setObjectName("label_motor_value_7")
        self.label_motor_value_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_motor_value_8.setGeometry(QtCore.QRect(320, 640, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_motor_value_8.setFont(font)
        self.label_motor_value_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor_value_8.setObjectName("label_motor_value_8")
        self.label_motor_value_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_motor_value_9.setGeometry(QtCore.QRect(60, 240, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_motor_value_9.setFont(font)
        self.label_motor_value_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor_value_9.setObjectName("label_motor_value_9")
        self.label_motor_value_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_motor_value_2.setGeometry(QtCore.QRect(990, 390, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_motor_value_2.setFont(font)
        self.label_motor_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor_value_2.setObjectName("label_motor_value_2")
        self.label_motor_value_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_motor_value_1.setGeometry(QtCore.QRect(1130, 190, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_motor_value_1.setFont(font)
        self.label_motor_value_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor_value_1.setObjectName("label_motor_value_1")
        self.label_motor_value_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_motor_value_3.setGeometry(QtCore.QRect(800, 190, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_motor_value_3.setFont(font)
        self.label_motor_value_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor_value_3.setObjectName("label_motor_value_3")
        self.Slider_4 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_4.setGeometry(QtCore.QRect(960, 680, 300, 30))
        self.Slider_4.setSliderPosition(0)
        self.Slider_4.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_4.setObjectName("Slider_4")
        self.Slider_5 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_5.setGeometry(QtCore.QRect(640, 680, 300, 30))
        self.Slider_5.setSliderPosition(0)
        self.Slider_5.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_5.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_5.setObjectName("Slider_5")
        self.Slider_8 = QtWidgets.QSlider(self.centralwidget)
        self.Slider_8.setGeometry(QtCore.QRect(310, 680, 300, 30))
        self.Slider_8.setSliderPosition(0)
        self.Slider_8.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_8.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_8.setObjectName("Slider_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_cw_2.setText(_translate("MainWindow", "CW"))
        self.pushButton_home_2.setText(_translate("MainWindow", "HOME"))
        self.pushButton_ccw_2.setText(_translate("MainWindow", "CCW"))
        self.lineEdit_pot_2.setText(_translate("MainWindow", "POT"))
        self.lineEdit_home_2.setText(_translate("MainWindow", "HOME"))
        self.lineEdit_not_2.setText(_translate("MainWindow", "NOT"))
        self.pushButton_cw_1.setText(_translate("MainWindow", "CW"))
        self.pushButton_home_1.setText(_translate("MainWindow", "HOME"))
        self.pushButton_ccw_1.setText(_translate("MainWindow", "CCW"))
        self.lineEdit_pot_1.setText(_translate("MainWindow", "POT"))
        self.lineEdit_home_1.setText(_translate("MainWindow", "HOME"))
        self.lineEdit_not_1.setText(_translate("MainWindow", "NOT"))
        self.pushButton_cw_3.setText(_translate("MainWindow", "CW"))
        self.lineEdit_pot_3.setText(_translate("MainWindow", "POT"))
        self.pushButton_home_3.setText(_translate("MainWindow", "HOME"))
        self.lineEdit_home_3.setText(_translate("MainWindow", "HOME"))
        self.pushButton_ccw_3.setText(_translate("MainWindow", "CCW"))
        self.lineEdit_not_3.setText(_translate("MainWindow", "NOT"))
        self.pushButton_cw_9.setText(_translate("MainWindow", "CW"))
        self.pushButton_home_9.setText(_translate("MainWindow", "HOME"))
        self.pushButton_ccw_9.setText(_translate("MainWindow", "CCW"))
        self.lineEdit_pot_9.setText(_translate("MainWindow", "POT"))
        self.lineEdit_home_9.setText(_translate("MainWindow", "HOME"))
        self.lineEdit_not_9.setText(_translate("MainWindow", "NOT"))
        self.pushButton_cw_8.setText(_translate("MainWindow", "CW"))
        self.pushButton_home_8.setText(_translate("MainWindow", "HOME"))
        self.pushButton_ccw_8.setText(_translate("MainWindow", "CCW"))
        self.lineEdit_pot_8.setText(_translate("MainWindow", "POT"))
        self.lineEdit_home_8.setText(_translate("MainWindow", "HOME"))
        self.lineEdit_not_8.setText(_translate("MainWindow", "NOT"))
        self.pushButton_cw_6.setText(_translate("MainWindow", "CW"))
        self.pushButton_home_6.setText(_translate("MainWindow", "HOME"))
        self.pushButton_ccw_6.setText(_translate("MainWindow", "CCW"))
        self.lineEdit_pot_6.setText(_translate("MainWindow", "POT"))
        self.lineEdit_home_6.setText(_translate("MainWindow", "HOME"))
        self.lineEdit_not_6.setText(_translate("MainWindow", "NOT"))
        self.pushButton_cw_5.setText(_translate("MainWindow", "CW"))
        self.pushButton_home_5.setText(_translate("MainWindow", "HOME"))
        self.pushButton_ccw_5.setText(_translate("MainWindow", "CCW"))
        self.lineEdit_pot_5.setText(_translate("MainWindow", "POT"))
        self.lineEdit_home_5.setText(_translate("MainWindow", "HOME"))
        self.lineEdit_not_5.setText(_translate("MainWindow", "NOT"))
        self.pushButton_cw_7.setText(_translate("MainWindow", "CW"))
        self.pushButton_home_7.setText(_translate("MainWindow", "HOME"))
        self.pushButton_ccw_7.setText(_translate("MainWindow", "CCW"))
        self.lineEdit_home_7.setText(_translate("MainWindow", "HOME"))
        self.lineEdit_not_7.setText(_translate("MainWindow", "NOT"))
        self.lineEdit_pot_7.setText(_translate("MainWindow", "POT"))
        self.pushButton_cw_4.setText(_translate("MainWindow", "CW"))
        self.pushButton_home_4.setText(_translate("MainWindow", "HOME"))
        self.pushButton_ccw_4.setText(_translate("MainWindow", "CCW"))
        self.lineEdit_pot_4.setText(_translate("MainWindow", "POT"))
        self.lineEdit_home_4.setText(_translate("MainWindow", "HOME"))
        self.lineEdit_not_4.setText(_translate("MainWindow", "NOT"))
        self.label_1.setText(_translate("MainWindow", "밸런스 1관절_모터"))
        self.label_3.setText(_translate("MainWindow", "밸런스 2관절 모터"))
        self.label_2.setText(_translate("MainWindow", "밸런스 텔레스코픽"))
        self.label_4.setText(_translate("MainWindow", "주행 모터"))
        self.label_5.setText(_translate("MainWindow", "메인 회전 모터"))
        self.label_6.setText(_translate("MainWindow", "서빙 텔레스코픽 모터"))
        self.label_7.setText(_translate("MainWindow", "서빙 이너 텔레스코픽"))
        self.label_8.setText(_translate("MainWindow", "서빙 회전 모터"))
        self.label_9.setText(_translate("MainWindow", "트레이 견인 모터"))
        self.label.setText(_translate("MainWindow", "Bumblebee Test Board"))
        self.label_motor_value_4.setText(_translate("MainWindow", "0"))
        self.label_motor_value_6.setText(_translate("MainWindow", "0"))
        self.label_motor_value_5.setText(_translate("MainWindow", "0"))
        self.label_motor_value_7.setText(_translate("MainWindow", "0"))
        self.label_motor_value_8.setText(_translate("MainWindow", "0"))
        self.label_motor_value_9.setText(_translate("MainWindow", "0"))
        self.label_motor_value_2.setText(_translate("MainWindow", "0"))
        self.label_motor_value_1.setText(_translate("MainWindow", "0"))
        self.label_motor_value_3.setText(_translate("MainWindow", "0"))
import main_rc
