# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1280, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1280, 400))
        MainWindow.setStyleSheet("background-color: #FFFFFF")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Korean, QtCore.QLocale.SouthKorea))
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1280, 400))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(105, 380))
        self.label_4.setMaximumSize(QtCore.QSize(140, 400))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 10px;border-color: beige;min-width: 5em;padding: 5px; }")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/res/bumblebee.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.floor_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.floor_label.sizePolicy().hasHeightForWidth())
        self.floor_label.setSizePolicy(sizePolicy)
        self.floor_label.setMinimumSize(QtCore.QSize(150, 200))
        self.floor_label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.floor_label.setFont(font)
        self.floor_label.setStyleSheet("QLabel {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 10px;border-color: beige; padding: 5px; }")
        self.floor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.floor_label.setObjectName("floor_label")
        self.verticalLayout_2.addWidget(self.floor_label)
        self.floor_up = QtWidgets.QPushButton(self.centralwidget)
        self.floor_up.setMinimumSize(QtCore.QSize(105, 165))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.floor_up.setFont(font)
        self.floor_up.setStyleSheet("QPushButton {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 15px;border-color: beige;min-width: 5em;padding: 5px; }\n"
"QPushButton:hover{background-color:#F0B93D;}")
        self.floor_up.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.floor_up.setObjectName("floor_up")
        self.verticalLayout_2.addWidget(self.floor_up)
        self.floor_reset = QtWidgets.QPushButton(self.centralwidget)
        self.floor_reset.setMinimumSize(QtCore.QSize(105, 70))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.floor_reset.setFont(font)
        self.floor_reset.setStyleSheet("QPushButton {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 15px;border-color: beige;min-width: 5em;padding: 5px; }\n"
"QPushButton:hover{background-color:#F0B93D;}")
        self.floor_reset.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.floor_reset.setObjectName("floor_reset")
        self.verticalLayout_2.addWidget(self.floor_reset)
        self.floor_down = QtWidgets.QPushButton(self.centralwidget)
        self.floor_down.setMinimumSize(QtCore.QSize(105, 165))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.floor_down.setFont(font)
        self.floor_down.setStyleSheet("QPushButton {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 15px;border-color: beige;min-width: 5em;padding: 5px; }\n"
"QPushButton:hover{background-color:#F0B93D;}")
        self.floor_down.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.floor_down.setObjectName("floor_down")
        self.verticalLayout_2.addWidget(self.floor_down)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(300, 400))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_3.setFont(font)
        self.label_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_3.setStyleSheet("QLabel {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 10px;border-color: beige;min-width: 2em;padding: 5px; }")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/res/tray.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(88, 180))
        self.label.setMaximumSize(QtCore.QSize(150, 195))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(70)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setStyleSheet("QLabel {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 10px;border-color: beige;min-width: 4em;padding: 5px; }")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.spinbox2 = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox2.sizePolicy().hasHeightForWidth())
        self.spinbox2.setSizePolicy(sizePolicy)
        self.spinbox2.setMinimumSize(QtCore.QSize(172, 180))
        self.spinbox2.setMaximumSize(QtCore.QSize(400, 195))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.spinbox2.setFont(font)
        self.spinbox2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinbox2.setAcceptDrops(False)
        self.spinbox2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinbox2.setAutoFillBackground(False)
        self.spinbox2.setStyleSheet("QSpinBox::up-button { width: 100px;} QSpinBox::down-button { width: 100px;}\n"
"QSpinBox {border-style: none; border-width: 1px; border-radius: 10px;border-color: #FDDE45;min-width: 10em;padding: 1px; }")
        self.spinbox2.setWrapping(True)
        self.spinbox2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox2.setReadOnly(False)
        self.spinbox2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinbox2.setAccelerated(True)
        self.spinbox2.setKeyboardTracking(True)
        self.spinbox2.setMaximum(10)
        self.spinbox2.setObjectName("spinbox2")
        self.horizontalLayout_5.addWidget(self.spinbox2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(88, 180))
        self.label_2.setMaximumSize(QtCore.QSize(150, 195))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(70)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(False)
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setStyleSheet("QLabel {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 10px;border-color: beige;min-width: 4em;padding: 5px; }")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.spinbox1 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinbox1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox1.sizePolicy().hasHeightForWidth())
        self.spinbox1.setSizePolicy(sizePolicy)
        self.spinbox1.setMinimumSize(QtCore.QSize(172, 180))
        self.spinbox1.setMaximumSize(QtCore.QSize(400, 195))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.spinbox1.setFont(font)
        self.spinbox1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinbox1.setStyleSheet("QSpinBox::up-button { width: 100px;} QSpinBox::down-button { width: 100px;}\n"
"QSpinBox {border-style: none; border-width: 1px; border-radius: 10px;border-color: #FDDE45;min-width: 10em;padding: 1px; }")
        self.spinbox1.setWrapping(True)
        self.spinbox1.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox1.setReadOnly(False)
        self.spinbox1.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinbox1.setAccelerated(True)
        self.spinbox1.setKeyboardTracking(True)
        self.spinbox1.setMaximum(10)
        self.spinbox1.setObjectName("spinbox1")
        self.horizontalLayout_6.addWidget(self.spinbox1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(105, 380))
        self.pushButton.setMaximumSize(QtCore.QSize(270, 400))
        self.pushButton.setBaseSize(QtCore.QSize(270, 390))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 10px;border-color: beige;min-width: 5em;padding: 5px; }\n"
"QPushButton:hover{background-color:#F0B93D;}")
        self.pushButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.evt_send_message)
        self.floor_reset.clicked.connect(MainWindow.evt_floor_default)
        self.floor_up.pressed.connect(MainWindow.evt_floor_up_pressed)
        self.floor_up.released.connect(MainWindow.evt_floor_up_released)
        # self.floor_up.clicked.connect(MainWindow.evt_floor_up)
        self.floor_down.pressed.connect(MainWindow.evt_floor_down_pressed)
        self.floor_down.released.connect(MainWindow.evt_floor_down_released)
        # self.floor_down.clicked.connect(MainWindow.evt_floor_down)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.floor_label.setText(_translate("MainWindow", "0"))
        self.floor_up.setText(_translate("MainWindow", "Up"))
        self.floor_reset.setText(_translate("MainWindow", "Reset"))
        self.floor_down.setText(_translate("MainWindow", "Down"))
        self.label.setText(_translate("MainWindow", "B"))
        self.label_2.setText(_translate("MainWindow", "A"))
import main_rc
