# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/ui/motor/sensorTest.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 441)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(380, 10, 230, 90))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 60, 32, 20))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.lineEdit_DI_7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_DI_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_DI_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_DI_7.setSizePolicy(sizePolicy)
        self.lineEdit_DI_7.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.lineEdit_DI_7.setFont(font)
        self.lineEdit_DI_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DI_7.setObjectName("lineEdit_DI_7")
        self.verticalLayout_3.addWidget(self.lineEdit_DI_7)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 30, 32, 20))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_state_1 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state_1.sizePolicy().hasHeightForWidth())
        self.label_state_1.setSizePolicy(sizePolicy)
        self.label_state_1.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_state_1.setFont(font)
        self.label_state_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_1.setWordWrap(True)
        self.label_state_1.setObjectName("label_state_1")
        self.verticalLayout_12.addWidget(self.label_state_1)
        self.lineEdit_state_1 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_state_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_state_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_state_1.setSizePolicy(sizePolicy)
        self.lineEdit_state_1.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_state_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_state_1.setObjectName("lineEdit_state_1")
        self.verticalLayout_12.addWidget(self.lineEdit_state_1)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_5.setGeometry(QtCore.QRect(160, 30, 32, 20))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_state_5 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state_5.sizePolicy().hasHeightForWidth())
        self.label_state_5.setSizePolicy(sizePolicy)
        self.label_state_5.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_state_5.setFont(font)
        self.label_state_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_5.setWordWrap(False)
        self.label_state_5.setObjectName("label_state_5")
        self.verticalLayout_15.addWidget(self.label_state_5)
        self.lineEdit_state_5 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_state_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_state_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_state_5.setSizePolicy(sizePolicy)
        self.lineEdit_state_5.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_state_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_state_5.setObjectName("lineEdit_state_5")
        self.verticalLayout_15.addWidget(self.lineEdit_state_5)
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_6.setGeometry(QtCore.QRect(190, 30, 32, 20))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_state_6 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state_6.sizePolicy().hasHeightForWidth())
        self.label_state_6.setSizePolicy(sizePolicy)
        self.label_state_6.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_state_6.setFont(font)
        self.label_state_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_6.setWordWrap(False)
        self.label_state_6.setObjectName("label_state_6")
        self.verticalLayout_16.addWidget(self.label_state_6)
        self.lineEdit_state_6 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_state_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_state_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_state_6.setSizePolicy(sizePolicy)
        self.lineEdit_state_6.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_state_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_state_6.setObjectName("lineEdit_state_6")
        self.verticalLayout_16.addWidget(self.lineEdit_state_6)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(130, 30, 32, 20))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_state_4 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state_4.sizePolicy().hasHeightForWidth())
        self.label_state_4.setSizePolicy(sizePolicy)
        self.label_state_4.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_state_4.setFont(font)
        self.label_state_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_4.setWordWrap(False)
        self.label_state_4.setObjectName("label_state_4")
        self.verticalLayout_14.addWidget(self.label_state_4)
        self.lineEdit_state_4 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_state_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_state_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_state_4.setSizePolicy(sizePolicy)
        self.lineEdit_state_4.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_state_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_state_4.setObjectName("lineEdit_state_4")
        self.verticalLayout_14.addWidget(self.lineEdit_state_4)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(70, 30, 32, 20))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_state_2 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state_2.sizePolicy().hasHeightForWidth())
        self.label_state_2.setSizePolicy(sizePolicy)
        self.label_state_2.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_state_2.setFont(font)
        self.label_state_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_2.setWordWrap(True)
        self.label_state_2.setObjectName("label_state_2")
        self.verticalLayout_13.addWidget(self.label_state_2)
        self.lineEdit_state_2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_state_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_state_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_state_2.setSizePolicy(sizePolicy)
        self.lineEdit_state_2.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_state_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_state_2.setObjectName("lineEdit_state_2")
        self.verticalLayout_13.addWidget(self.lineEdit_state_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 32, 20))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_state_0 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state_0.sizePolicy().hasHeightForWidth())
        self.label_state_0.setSizePolicy(sizePolicy)
        self.label_state_0.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_state_0.setFont(font)
        self.label_state_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state_0.setWordWrap(True)
        self.label_state_0.setObjectName("label_state_0")
        self.verticalLayout_11.addWidget(self.label_state_0)
        self.lineEdit_state_0 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_state_0.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_state_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_state_0.setSizePolicy(sizePolicy)
        self.lineEdit_state_0.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_state_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_state_0.setObjectName("lineEdit_state_0")
        self.verticalLayout_11.addWidget(self.lineEdit_state_0)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(70, 60, 32, 20))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.lineEdit_POT = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_POT.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_POT.sizePolicy().hasHeightForWidth())
        self.lineEdit_POT.setSizePolicy(sizePolicy)
        self.lineEdit_POT.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.lineEdit_POT.setFont(font)
        self.lineEdit_POT.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_POT.setObjectName("lineEdit_POT")
        self.verticalLayout_7.addWidget(self.lineEdit_POT)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 60, 32, 20))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.lineEdit_DI_1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_DI_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_DI_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_DI_1.setSizePolicy(sizePolicy)
        self.lineEdit_DI_1.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.lineEdit_DI_1.setFont(font)
        self.lineEdit_DI_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DI_1.setObjectName("lineEdit_DI_1")
        self.verticalLayout.addWidget(self.lineEdit_DI_1)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(130, 60, 32, 20))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.lineEdit_HOME = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_HOME.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_HOME.sizePolicy().hasHeightForWidth())
        self.lineEdit_HOME.setSizePolicy(sizePolicy)
        self.lineEdit_HOME.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.lineEdit_HOME.setFont(font)
        self.lineEdit_HOME.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_HOME.setObjectName("lineEdit_HOME")
        self.verticalLayout_5.addWidget(self.lineEdit_HOME)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(100, 60, 32, 20))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.lineEdit_STOP = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_STOP.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_STOP.sizePolicy().hasHeightForWidth())
        self.lineEdit_STOP.setSizePolicy(sizePolicy)
        self.lineEdit_STOP.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.lineEdit_STOP.setFont(font)
        self.lineEdit_STOP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_STOP.setObjectName("lineEdit_STOP")
        self.verticalLayout_6.addWidget(self.lineEdit_STOP)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(160, 60, 32, 20))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.lineEdit_DI_6 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_DI_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_DI_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_DI_6.setSizePolicy(sizePolicy)
        self.lineEdit_DI_6.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.lineEdit_DI_6.setFont(font)
        self.lineEdit_DI_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DI_6.setObjectName("lineEdit_DI_6")
        self.verticalLayout_4.addWidget(self.lineEdit_DI_6)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(40, 60, 32, 20))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.lineEdit_NOT = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_NOT.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_NOT.sizePolicy().hasHeightForWidth())
        self.lineEdit_NOT.setSizePolicy(sizePolicy)
        self.lineEdit_NOT.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.lineEdit_NOT.setFont(font)
        self.lineEdit_NOT.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_NOT.setObjectName("lineEdit_NOT")
        self.verticalLayout_2.addWidget(self.lineEdit_NOT)
        self.layoutWidget8 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 110, 600, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget8.sizePolicy().hasHeightForWidth())
        self.layoutWidget8.setSizePolicy(sizePolicy)
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget8)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_ACC = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ACC.sizePolicy().hasHeightForWidth())
        self.label_ACC.setSizePolicy(sizePolicy)
        self.label_ACC.setMinimumSize(QtCore.QSize(38, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ACC.setFont(font)
        self.label_ACC.setStyleSheet("QLabel {background-color: \'gray\';border-style: outset; border-width: 1px; border-radius: 10px;border-color: beige;min-width: 2em;padding: 1px; }")
        self.label_ACC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ACC.setObjectName("label_ACC")
        self.gridLayout.addWidget(self.label_ACC, 0, 5, 1, 1)
        self.lineEdit_POS = QtWidgets.QLineEdit(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_POS.sizePolicy().hasHeightForWidth())
        self.lineEdit_POS.setSizePolicy(sizePolicy)
        self.lineEdit_POS.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_POS.setObjectName("lineEdit_POS")
        self.gridLayout.addWidget(self.lineEdit_POS, 1, 3, 1, 1)
        self.label_SPEED = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SPEED.sizePolicy().hasHeightForWidth())
        self.label_SPEED.setSizePolicy(sizePolicy)
        self.label_SPEED.setMinimumSize(QtCore.QSize(38, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_SPEED.setFont(font)
        self.label_SPEED.setStyleSheet("QLabel {background-color: \'gray\';border-style: outset; border-width: 1px; border-radius: 10px;border-color: beige;min-width: 2em;padding: 1px; }")
        self.label_SPEED.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SPEED.setObjectName("label_SPEED")
        self.gridLayout.addWidget(self.label_SPEED, 0, 4, 1, 1)
        self.label_CMD = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CMD.sizePolicy().hasHeightForWidth())
        self.label_CMD.setSizePolicy(sizePolicy)
        self.label_CMD.setMinimumSize(QtCore.QSize(38, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_CMD.setFont(font)
        self.label_CMD.setStyleSheet("QLabel {background-color: \'gray\';border-style: outset; border-width: 1px; border-radius: 10px;border-color: beige;min-width: 2em;padding: 1px; }")
        self.label_CMD.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CMD.setObjectName("label_CMD")
        self.gridLayout.addWidget(self.label_CMD, 0, 0, 1, 1)
        self.lineEdit_MODE = QtWidgets.QLineEdit(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MODE.sizePolicy().hasHeightForWidth())
        self.lineEdit_MODE.setSizePolicy(sizePolicy)
        self.lineEdit_MODE.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MODE.setObjectName("lineEdit_MODE")
        self.gridLayout.addWidget(self.lineEdit_MODE, 1, 2, 1, 1)
        self.lineEdit_SPD = QtWidgets.QLineEdit(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SPD.sizePolicy().hasHeightForWidth())
        self.lineEdit_SPD.setSizePolicy(sizePolicy)
        self.lineEdit_SPD.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SPD.setObjectName("lineEdit_SPD")
        self.gridLayout.addWidget(self.lineEdit_SPD, 1, 4, 1, 1)
        self.label_MBID = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MBID.sizePolicy().hasHeightForWidth())
        self.label_MBID.setSizePolicy(sizePolicy)
        self.label_MBID.setMinimumSize(QtCore.QSize(38, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_MBID.setFont(font)
        self.label_MBID.setStyleSheet("QLabel {background-color: \'gray\';border-style: outset; border-width: 1px; border-radius: 10px;border-color: beige;min-width: 2em;padding: 1px; }")
        self.label_MBID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_MBID.setObjectName("label_MBID")
        self.gridLayout.addWidget(self.label_MBID, 0, 1, 1, 1)
        self.label_MODE = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MODE.sizePolicy().hasHeightForWidth())
        self.label_MODE.setSizePolicy(sizePolicy)
        self.label_MODE.setMinimumSize(QtCore.QSize(38, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_MODE.setFont(font)
        self.label_MODE.setStyleSheet("QLabel {background-color: \'gray\';border-style: outset; border-width: 1px; border-radius: 10px;border-color: beige;min-width: 2em;padding: 1px; }")
        self.label_MODE.setAlignment(QtCore.Qt.AlignCenter)
        self.label_MODE.setObjectName("label_MODE")
        self.gridLayout.addWidget(self.label_MODE, 0, 2, 1, 1)
        self.label_DECC = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_DECC.sizePolicy().hasHeightForWidth())
        self.label_DECC.setSizePolicy(sizePolicy)
        self.label_DECC.setMinimumSize(QtCore.QSize(38, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_DECC.setFont(font)
        self.label_DECC.setStyleSheet("QLabel {background-color: \'gray\';border-style: outset; border-width: 1px; border-radius: 10px;border-color: beige;min-width: 2em;padding: 1px; }")
        self.label_DECC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DECC.setObjectName("label_DECC")
        self.gridLayout.addWidget(self.label_DECC, 0, 6, 1, 1)
        self.lineEdit_DECC = QtWidgets.QLineEdit(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_DECC.sizePolicy().hasHeightForWidth())
        self.lineEdit_DECC.setSizePolicy(sizePolicy)
        self.lineEdit_DECC.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_DECC.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_DECC.setObjectName("lineEdit_DECC")
        self.gridLayout.addWidget(self.lineEdit_DECC, 1, 6, 1, 1)
        self.lineEdit_MBID = QtWidgets.QLineEdit(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_MBID.sizePolicy().hasHeightForWidth())
        self.lineEdit_MBID.setSizePolicy(sizePolicy)
        self.lineEdit_MBID.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_MBID.setObjectName("lineEdit_MBID")
        self.gridLayout.addWidget(self.lineEdit_MBID, 1, 1, 1, 1)
        self.lineEdit_ACC = QtWidgets.QLineEdit(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ACC.sizePolicy().hasHeightForWidth())
        self.lineEdit_ACC.setSizePolicy(sizePolicy)
        self.lineEdit_ACC.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_ACC.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ACC.setObjectName("lineEdit_ACC")
        self.gridLayout.addWidget(self.lineEdit_ACC, 1, 5, 1, 1)
        self.label_POS = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_POS.sizePolicy().hasHeightForWidth())
        self.label_POS.setSizePolicy(sizePolicy)
        self.label_POS.setMinimumSize(QtCore.QSize(38, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_POS.setFont(font)
        self.label_POS.setStyleSheet("QLabel {background-color: \'gray\';border-style: outset; border-width: 1px; border-radius: 10px;border-color: beige;min-width: 2em;padding: 1px; }")
        self.label_POS.setAlignment(QtCore.Qt.AlignCenter)
        self.label_POS.setObjectName("label_POS")
        self.gridLayout.addWidget(self.label_POS, 0, 3, 1, 1)
        self.comboBox_CMD = QtWidgets.QComboBox(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_CMD.sizePolicy().hasHeightForWidth())
        self.comboBox_CMD.setSizePolicy(sizePolicy)
        self.comboBox_CMD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_CMD.setObjectName("comboBox_CMD")
        self.comboBox_CMD.addItem("")
        self.comboBox_CMD.addItem("")
        self.comboBox_CMD.addItem("")
        self.comboBox_CMD.addItem("")
        self.comboBox_CMD.addItem("")
        self.comboBox_CMD.addItem("")
        self.comboBox_CMD.addItem("")
        self.comboBox_CMD.addItem("")
        self.comboBox_CMD.addItem("")
        self.comboBox_CMD.addItem("")
        self.comboBox_CMD.addItem("")
        self.gridLayout.addWidget(self.comboBox_CMD, 1, 0, 1, 1)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setEnabled(True)
        self.logo.setGeometry(QtCore.QRect(10, 0, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("/root/ui/motor/../resource/new_bumbkebee.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 270, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Com_Receive_PlainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Com_Receive_PlainTextEdit.setGeometry(QtCore.QRect(10, 200, 601, 231))
        self.Com_Receive_PlainTextEdit.setObjectName("Com_Receive_PlainTextEdit")
        self.layoutWidget9 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget9.setGeometry(QtCore.QRect(11, 170, 601, 27))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Com_isOpenOrNot_Label = QtWidgets.QLabel(self.layoutWidget9)
        self.Com_isOpenOrNot_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Com_isOpenOrNot_Label.setObjectName("Com_isOpenOrNot_Label")
        self.horizontalLayout_2.addWidget(self.Com_isOpenOrNot_Label)
        self.Com_Name_Combo = QtWidgets.QComboBox(self.layoutWidget9)
        self.Com_Name_Combo.setObjectName("Com_Name_Combo")
        self.horizontalLayout_2.addWidget(self.Com_Name_Combo)
        self.Com_Baud_Combo = QtWidgets.QComboBox(self.layoutWidget9)
        self.Com_Baud_Combo.setObjectName("Com_Baud_Combo")
        self.horizontalLayout_2.addWidget(self.Com_Baud_Combo)
        self.Com_Refresh_Button = QtWidgets.QPushButton(self.layoutWidget9)
        self.Com_Refresh_Button.setObjectName("Com_Refresh_Button")
        self.horizontalLayout_2.addWidget(self.Com_Refresh_Button)
        self.Com_Clear_Button = QtWidgets.QPushButton(self.layoutWidget9)
        self.Com_Clear_Button.setObjectName("Com_Clear_Button")
        self.horizontalLayout_2.addWidget(self.Com_Clear_Button)
        self.Com_Open_Button = QtWidgets.QPushButton(self.layoutWidget9)
        self.Com_Open_Button.setObjectName("Com_Open_Button")
        self.horizontalLayout_2.addWidget(self.Com_Open_Button)
        self.Com_Close_Button = QtWidgets.QPushButton(self.layoutWidget9)
        self.Com_Close_Button.setObjectName("Com_Close_Button")
        self.horizontalLayout_2.addWidget(self.Com_Close_Button)
        self.pushButton_STOP = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_STOP.setEnabled(True)
        self.pushButton_STOP.setGeometry(QtCore.QRect(310, 80, 60, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_STOP.sizePolicy().hasHeightForWidth())
        self.pushButton_STOP.setSizePolicy(sizePolicy)
        self.pushButton_STOP.setBaseSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_STOP.setFont(font)
        self.pushButton_STOP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_STOP.setAutoDefault(False)
        self.pushButton_STOP.setDefault(False)
        self.pushButton_STOP.setFlat(False)
        self.pushButton_STOP.setObjectName("pushButton_STOP")
        self.pushButton_RESET = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_RESET.setEnabled(True)
        self.pushButton_RESET.setGeometry(QtCore.QRect(170, 80, 60, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RESET.sizePolicy().hasHeightForWidth())
        self.pushButton_RESET.setSizePolicy(sizePolicy)
        self.pushButton_RESET.setBaseSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_RESET.setFont(font)
        self.pushButton_RESET.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_RESET.setAutoDefault(False)
        self.pushButton_RESET.setDefault(False)
        self.pushButton_RESET.setFlat(False)
        self.pushButton_RESET.setObjectName("pushButton_RESET")
        self.comboBox_MBID = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_MBID.setGeometry(QtCore.QRect(11, 80, 81, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_MBID.sizePolicy().hasHeightForWidth())
        self.comboBox_MBID.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.comboBox_MBID.setFont(font)
        self.comboBox_MBID.setObjectName("comboBox_MBID")
        self.comboBox_MBID.addItem("")
        self.comboBox_MBID.addItem("")
        self.comboBox_MBID.addItem("")
        self.comboBox_MBID.addItem("")
        self.comboBox_MBID.addItem("")
        self.comboBox_MBID.addItem("")
        self.comboBox_MBID.addItem("")
        self.comboBox_MBID.addItem("")
        self.pushButton_START = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_START.setEnabled(True)
        self.pushButton_START.setGeometry(QtCore.QRect(240, 80, 60, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_START.sizePolicy().hasHeightForWidth())
        self.pushButton_START.setSizePolicy(sizePolicy)
        self.pushButton_START.setBaseSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_START.setFont(font)
        self.pushButton_START.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_START.setAutoDefault(False)
        self.pushButton_START.setDefault(False)
        self.pushButton_START.setFlat(False)
        self.pushButton_START.setObjectName("pushButton_START")
        self.pushButton_READ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_READ.setEnabled(True)
        self.pushButton_READ.setGeometry(QtCore.QRect(100, 80, 60, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_READ.sizePolicy().hasHeightForWidth())
        self.pushButton_READ.setSizePolicy(sizePolicy)
        self.pushButton_READ.setBaseSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_READ.setFont(font)
        self.pushButton_READ.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_READ.setAutoDefault(False)
        self.pushButton_READ.setDefault(False)
        self.pushButton_READ.setFlat(False)
        self.pushButton_READ.setObjectName("pushButton_READ")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_CMD, self.lineEdit_MBID)
        MainWindow.setTabOrder(self.lineEdit_MBID, self.lineEdit_MODE)
        MainWindow.setTabOrder(self.lineEdit_MODE, self.lineEdit_POS)
        MainWindow.setTabOrder(self.lineEdit_POS, self.lineEdit_SPD)
        MainWindow.setTabOrder(self.lineEdit_SPD, self.lineEdit_ACC)
        MainWindow.setTabOrder(self.lineEdit_ACC, self.lineEdit_DECC)
        MainWindow.setTabOrder(self.lineEdit_DECC, self.Com_Name_Combo)
        MainWindow.setTabOrder(self.Com_Name_Combo, self.Com_Baud_Combo)
        MainWindow.setTabOrder(self.Com_Baud_Combo, self.Com_Refresh_Button)
        MainWindow.setTabOrder(self.Com_Refresh_Button, self.Com_Clear_Button)
        MainWindow.setTabOrder(self.Com_Clear_Button, self.Com_Open_Button)
        MainWindow.setTabOrder(self.Com_Open_Button, self.Com_Close_Button)
        MainWindow.setTabOrder(self.Com_Close_Button, self.Com_Receive_PlainTextEdit)
        MainWindow.setTabOrder(self.Com_Receive_PlainTextEdit, self.comboBox_MBID)
        MainWindow.setTabOrder(self.comboBox_MBID, self.pushButton_READ)
        MainWindow.setTabOrder(self.pushButton_READ, self.pushButton_RESET)
        MainWindow.setTabOrder(self.pushButton_RESET, self.pushButton_START)
        MainWindow.setTabOrder(self.pushButton_START, self.lineEdit_DI_6)
        MainWindow.setTabOrder(self.lineEdit_DI_6, self.lineEdit_state_5)
        MainWindow.setTabOrder(self.lineEdit_state_5, self.lineEdit_state_0)
        MainWindow.setTabOrder(self.lineEdit_state_0, self.lineEdit_POT)
        MainWindow.setTabOrder(self.lineEdit_POT, self.lineEdit_NOT)
        MainWindow.setTabOrder(self.lineEdit_NOT, self.lineEdit_state_4)
        MainWindow.setTabOrder(self.lineEdit_state_4, self.lineEdit_state_2)
        MainWindow.setTabOrder(self.lineEdit_state_2, self.pushButton_STOP)
        MainWindow.setTabOrder(self.pushButton_STOP, self.lineEdit_DI_1)
        MainWindow.setTabOrder(self.lineEdit_DI_1, self.lineEdit_DI_7)
        MainWindow.setTabOrder(self.lineEdit_DI_7, self.lineEdit_HOME)
        MainWindow.setTabOrder(self.lineEdit_HOME, self.lineEdit_STOP)
        MainWindow.setTabOrder(self.lineEdit_STOP, self.lineEdit_state_1)
        MainWindow.setTabOrder(self.lineEdit_state_1, self.lineEdit_state_6)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_10.setText(_translate("MainWindow", "DI_7"))
        self.label_state_1.setText(_translate("MainWindow", "Enable"))
        self.label_state_5.setText(_translate("MainWindow", "Path"))
        self.label_state_6.setText(_translate("MainWindow", "Home"))
        self.label_state_4.setText(_translate("MainWindow", "Cmd"))
        self.label_state_2.setText(_translate("MainWindow", "Run"))
        self.label_state_0.setText(_translate("MainWindow", "Faulty"))
        self.label_4.setText(_translate("MainWindow", "POT"))
        self.label_8.setText(_translate("MainWindow", "DI_1"))
        self.label_6.setText(_translate("MainWindow", "HOME"))
        self.label_7.setText(_translate("MainWindow", "STOP"))
        self.label_9.setText(_translate("MainWindow", "DI_6"))
        self.label_5.setText(_translate("MainWindow", "NOT"))
        self.label_ACC.setText(_translate("MainWindow", "ACC"))
        self.label_SPEED.setText(_translate("MainWindow", "SPEED"))
        self.label_CMD.setText(_translate("MainWindow", "CMD"))
        self.label_MBID.setText(_translate("MainWindow", "MBID"))
        self.label_MODE.setText(_translate("MainWindow", "MODE"))
        self.label_DECC.setText(_translate("MainWindow", "DECC"))
        self.label_POS.setText(_translate("MainWindow", "POS"))
        self.comboBox_CMD.setItemText(0, _translate("MainWindow", "WMOVE"))
        self.comboBox_CMD.setItemText(1, _translate("MainWindow", "WSTOP"))
        self.comboBox_CMD.setItemText(2, _translate("MainWindow", "WSETUP"))
        self.comboBox_CMD.setItemText(3, _translate("MainWindow", "WINIT"))
        self.comboBox_CMD.setItemText(4, _translate("MainWindow", "WLIMIT"))
        self.comboBox_CMD.setItemText(5, _translate("MainWindow", "WLIMIT_OFF"))
        self.comboBox_CMD.setItemText(6, _translate("MainWindow", "WOFF"))
        self.comboBox_CMD.setItemText(7, _translate("MainWindow", "WALM_C"))
        self.comboBox_CMD.setItemText(8, _translate("MainWindow", "WZERO"))
        self.comboBox_CMD.setItemText(9, _translate("MainWindow", "WLOC"))
        self.comboBox_CMD.setItemText(10, _translate("MainWindow", "WSPD"))
        self.label_2.setText(_translate("MainWindow", "TacTracer"))
        self.Com_isOpenOrNot_Label.setText(_translate("MainWindow", "Serial"))
        self.Com_Refresh_Button.setText(_translate("MainWindow", "Refresh"))
        self.Com_Clear_Button.setText(_translate("MainWindow", "Clear"))
        self.Com_Open_Button.setText(_translate("MainWindow", "Open"))
        self.Com_Close_Button.setText(_translate("MainWindow", "Close"))
        self.pushButton_STOP.setText(_translate("MainWindow", "STOP"))
        self.pushButton_RESET.setText(_translate("MainWindow", "RESET"))
        self.comboBox_MBID.setItemText(0, _translate("MainWindow", "MB_30"))
        self.comboBox_MBID.setItemText(1, _translate("MainWindow", "MB_24"))
        self.comboBox_MBID.setItemText(2, _translate("MainWindow", "MB_25"))
        self.comboBox_MBID.setItemText(3, _translate("MainWindow", "MB_26"))
        self.comboBox_MBID.setItemText(4, _translate("MainWindow", "MB_27"))
        self.comboBox_MBID.setItemText(5, _translate("MainWindow", "MB_28"))
        self.comboBox_MBID.setItemText(6, _translate("MainWindow", "MB_29"))
        self.comboBox_MBID.setItemText(7, _translate("MainWindow", "MB_31"))
        self.pushButton_START.setText(_translate("MainWindow", "START"))
        self.pushButton_READ.setText(_translate("MainWindow", "READ"))
