# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/ui/setting_info.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingInfoForm(object):
    def setupUi(self, settingForm):
        settingForm.setObjectName("settingForm")
        settingForm.resize(1280, 400)
        settingForm.setStyleSheet("background-color: #FDDE45")
        self.verticalLayoutWidget = QtWidgets.QWidget(settingForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 1261, 271))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_infomation = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_infomation.setFont(font)
        self.lbl_infomation.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_infomation.setObjectName("lbl_infomation")
        self.verticalLayout.addWidget(self.lbl_infomation)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, -1, 5, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lbl_device = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_device.setFont(font)
        self.lbl_device.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_device.setObjectName("lbl_device")
        self.verticalLayout_9.addWidget(self.lbl_device)
        self.lbl_model = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_model.setFont(font)
        self.lbl_model.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_model.setObjectName("lbl_model")
        self.verticalLayout_9.addWidget(self.lbl_model)
        self.lbl_serial_no = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_serial_no.setFont(font)
        self.lbl_serial_no.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_serial_no.setObjectName("lbl_serial_no")
        self.verticalLayout_9.addWidget(self.lbl_serial_no)
        self.lbl_part_no = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_part_no.setFont(font)
        self.lbl_part_no.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_part_no.setObjectName("lbl_part_no")
        self.verticalLayout_9.addWidget(self.lbl_part_no)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lbl_device_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_device_value.setFont(font)
        self.lbl_device_value.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_device_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_device_value.setObjectName("lbl_device_value")
        self.verticalLayout_13.addWidget(self.lbl_device_value)
        self.lbl_model_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_model_value.setFont(font)
        self.lbl_model_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_model_value.setObjectName("lbl_model_value")
        self.verticalLayout_13.addWidget(self.lbl_model_value)
        self.lbl_serial_no_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_serial_no_value.setFont(font)
        self.lbl_serial_no_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_serial_no_value.setObjectName("lbl_serial_no_value")
        self.verticalLayout_13.addWidget(self.lbl_serial_no_value)
        self.lbl_part_no_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_part_no_value.setFont(font)
        self.lbl_part_no_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_part_no_value.setObjectName("lbl_part_no_value")
        self.verticalLayout_13.addWidget(self.lbl_part_no_value)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, -1, 5, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lbl_software = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_software.setFont(font)
        self.lbl_software.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_software.setObjectName("lbl_software")
        self.verticalLayout_12.addWidget(self.lbl_software)
        self.lbl_hardware = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hardware.setFont(font)
        self.lbl_hardware.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_hardware.setObjectName("lbl_hardware")
        self.verticalLayout_12.addWidget(self.lbl_hardware)
        self.lbl_manufacuring = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_manufacuring.setFont(font)
        self.lbl_manufacuring.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_manufacuring.setObjectName("lbl_manufacuring")
        self.verticalLayout_12.addWidget(self.lbl_manufacuring)
        self.lbl_datacode = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_datacode.setFont(font)
        self.lbl_datacode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_datacode.setObjectName("lbl_datacode")
        self.verticalLayout_12.addWidget(self.lbl_datacode)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lbl_software_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_software_value.setFont(font)
        self.lbl_software_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_software_value.setObjectName("lbl_software_value")
        self.verticalLayout_11.addWidget(self.lbl_software_value)
        self.lbl_hardware_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_hardware_value.setFont(font)
        self.lbl_hardware_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_hardware_value.setObjectName("lbl_hardware_value")
        self.verticalLayout_11.addWidget(self.lbl_hardware_value)
        self.lbl_manufacuring_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_manufacuring_value.setFont(font)
        self.lbl_manufacuring_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_manufacuring_value.setObjectName("lbl_manufacuring_value")
        self.verticalLayout_11.addWidget(self.lbl_manufacuring_value)
        self.lbl_datacode_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_datacode_value.setFont(font)
        self.lbl_datacode_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_datacode_value.setObjectName("lbl_datacode_value")
        self.verticalLayout_11.addWidget(self.lbl_datacode_value)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(1, 4)
        self.btn_return = QtWidgets.QPushButton(settingForm)
        self.btn_return.setGeometry(QtCore.QRect(10, 10, 100, 50))
        self.btn_return.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_return.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_return.setFont(font)
        self.btn_return.setStyleSheet("QPushButton{\n"
"    color: #FDDE45;\n"
"    background-color: #FDDE45;\n"
"    border: 2px solid #A6A7A9;\n"
"    border-radius: 20px;\n"
"}")
        self.btn_return.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_return.setIcon(icon)
        self.btn_return.setIconSize(QtCore.QSize(32, 32))
        self.btn_return.setObjectName("btn_return_2")

        self.retranslateUi(settingForm)
        self.btn_return.clicked.connect(settingForm.evt_return)
        QtCore.QMetaObject.connectSlotsByName(settingForm)

    def retranslateUi(self, settingForm):
        _translate = QtCore.QCoreApplication.translate
        settingForm.setWindowTitle(_translate("settingForm", "Form"))
        self.lbl_infomation.setText(_translate("settingForm", "Infomation"))
        self.lbl_device.setText(_translate("settingForm", "Device"))
        self.lbl_model.setText(_translate("settingForm", "Model"))
        self.lbl_serial_no.setText(_translate("settingForm", "Serial No"))
        self.lbl_part_no.setText(_translate("settingForm", "Part No"))
        self.lbl_device_value.setText(_translate("settingForm", "BumbleBee"))
        self.lbl_model_value.setText(_translate("settingForm", "BumbleBee"))
        self.lbl_serial_no_value.setText(_translate("settingForm", "S1234567890"))
        self.lbl_part_no_value.setText(_translate("settingForm", "P9876543210"))
        self.lbl_software.setText(_translate("settingForm", "Software"))
        self.lbl_hardware.setText(_translate("settingForm", "Hardware"))
        self.lbl_manufacuring.setText(_translate("settingForm", "Manufacuring"))
        self.lbl_datacode.setText(_translate("settingForm", "Date Code"))
        self.lbl_software_value.setText(_translate("settingForm", "1.0.1"))
        self.lbl_hardware_value.setText(_translate("settingForm", "0.0.1"))
        self.lbl_manufacuring_value.setText(_translate("settingForm", "Tactracer"))
        self.lbl_datacode_value.setText(_translate("settingForm", "2023-08"))
import main_rc
