# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/ui/setting_language.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingLanguageForm(object):
    def setupUi(self, settingLanguageForm):
        settingLanguageForm.setObjectName("settingLanguageForm")
        settingLanguageForm.resize(1280, 400)
        settingLanguageForm.setStyleSheet("background-color: #FDDE45")
        self.verticalLayoutWidget = QtWidgets.QWidget(settingLanguageForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 60, 1261, 272))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_language = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_language.setFont(font)
        self.lbl_language.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_language.setObjectName("lbl_language")
        self.verticalLayout.addWidget(self.lbl_language)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn_language = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_language.setMinimumSize(QtCore.QSize(95, 150))
        self.btn_language.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_language.setFont(font)
        self.btn_language.setStyleSheet("QPushButton {color:#FDDE45;background-color: #A6A7A9;border-style: outset; border-width: 0px; border-radius: 75px;border-color: #FDDE45;min-width: 5em;padding: 5px; }")
        self.btn_language.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/flag/korea_flag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_language.setIcon(icon)
        self.btn_language.setIconSize(QtCore.QSize(150, 150))
        self.btn_language.setObjectName("btn_language")
        self.verticalLayout_6.addWidget(self.btn_language)
        self.lbl_korean = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_korean.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_korean.setFont(font)
        self.lbl_korean.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_korean.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_korean.setObjectName("lbl_korean")
        self.verticalLayout_6.addWidget(self.lbl_korean)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_battery = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_battery.setMinimumSize(QtCore.QSize(95, 150))
        self.btn_battery.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_battery.setFont(font)
        self.btn_battery.setStyleSheet("QPushButton {color:#FDDE45;background-color: #A6A7A9;border-style: outset; border-width: 0px; border-radius: 75px;border-color: #FDDE45;min-width: 5em;padding: 5px; }")
        self.btn_battery.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/flag/usa_flag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_battery.setIcon(icon1)
        self.btn_battery.setIconSize(QtCore.QSize(150, 150))
        self.btn_battery.setObjectName("btn_battery")
        self.verticalLayout_7.addWidget(self.btn_battery)
        self.lbl_english = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_english.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_english.setFont(font)
        self.lbl_english.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_english.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_english.setObjectName("lbl_english")
        self.verticalLayout_7.addWidget(self.lbl_english)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.btn_return = QtWidgets.QPushButton(settingLanguageForm)
        self.btn_return.setGeometry(QtCore.QRect(10, 10, 100, 50))
        self.btn_return.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_return.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_return.setFont(font)
        self.btn_return.setStyleSheet("QPushButton{\n"
"    color: #FDDE45;\n"
"    background-color: #FDDE45;\n"
"    border: 2px solid #A6A7A9;\n"
"    border-radius: 20px;\n"
"}")
        self.btn_return.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_return.setIcon(icon2)
        self.btn_return.setIconSize(QtCore.QSize(32, 32))
        self.btn_return.setFlat(True)
        self.btn_return.setObjectName("btn_return")

        self.retranslateUi(settingLanguageForm)
        self.btn_return.clicked.connect(settingLanguageForm.evt_return)
        self.btn_language.clicked.connect(settingLanguageForm.evt_clicked_korean)
        self.btn_battery.clicked.connect(settingLanguageForm.evt_clicked_english)
        QtCore.QMetaObject.connectSlotsByName(settingLanguageForm)

    def retranslateUi(self, settingLanguageForm):
        _translate = QtCore.QCoreApplication.translate
        settingLanguageForm.setWindowTitle(_translate("settingLanguageForm", "Form"))
        self.lbl_language.setText(_translate("settingLanguageForm", "Language"))
        self.lbl_korean.setText(_translate("settingLanguageForm", "Korean"))
        self.lbl_english.setText(_translate("settingLanguageForm", "English"))
import main_rc
