# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/ui/setting.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingForm(object):
    def setupUi(self, settingForm):
        settingForm.setObjectName("settingForm")
        settingForm.resize(1280, 400)
        settingForm.setStyleSheet("background-color: #FDDE45")
        self.layoutWidget = QtWidgets.QWidget(settingForm)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 110, 1261, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_setting = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_setting.setMinimumSize(QtCore.QSize(95, 150))
        self.btn_setting.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_setting.setFont(font)
        self.btn_setting.setStyleSheet("QPushButton {color:#FDDE45;background-color: #A6A7A9;border-style: outset; border-width: 0px; border-radius: 50px;border-color: #FDDE45;min-width: 5em;padding: 5px; }")
        self.btn_setting.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting.setIcon(icon)
        self.btn_setting.setIconSize(QtCore.QSize(75, 75))
        self.btn_setting.setObjectName("btn_setting")
        self.verticalLayout_5.addWidget(self.btn_setting)
        self.lbl_setting = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_setting.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_setting.setFont(font)
        self.lbl_setting.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_setting.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_setting.setObjectName("lbl_setting")
        self.verticalLayout_5.addWidget(self.lbl_setting)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn_language = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_language.setMinimumSize(QtCore.QSize(95, 150))
        self.btn_language.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_language.setFont(font)
        self.btn_language.setStyleSheet("QPushButton {color:#FDDE45;background-color: #A6A7A9;border-style: outset; border-width: 0px; border-radius: 50px;border-color: #FDDE45;min-width: 5em;padding: 5px; }")
        self.btn_language.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/language.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_language.setIcon(icon1)
        self.btn_language.setIconSize(QtCore.QSize(75, 75))
        self.btn_language.setObjectName("btn_language")
        self.verticalLayout_6.addWidget(self.btn_language)
        self.lbl_language = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_language.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_language.setFont(font)
        self.lbl_language.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_language.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_language.setObjectName("lbl_language")
        self.verticalLayout_6.addWidget(self.lbl_language)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_battery = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_battery.setMinimumSize(QtCore.QSize(95, 150))
        self.btn_battery.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_battery.setFont(font)
        self.btn_battery.setStyleSheet("QPushButton {color:#FDDE45;background-color: #A6A7A9;border-style: outset; border-width: 0px; border-radius: 50px;border-color: #FDDE45;min-width: 5em;padding: 5px; }")
        self.btn_battery.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/battery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_battery.setIcon(icon2)
        self.btn_battery.setIconSize(QtCore.QSize(75, 75))
        self.btn_battery.setObjectName("btn_battery")
        self.verticalLayout_7.addWidget(self.btn_battery)
        self.lbl_battery = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_battery.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_battery.setFont(font)
        self.lbl_battery.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_battery.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_battery.setObjectName("lbl_battery")
        self.verticalLayout_7.addWidget(self.lbl_battery)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_info = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_info.setMinimumSize(QtCore.QSize(95, 150))
        self.btn_info.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_info.setFont(font)
        self.btn_info.setStyleSheet("QPushButton {color:#FDDE45;background-color: #A6A7A9;border-style: outset; border-width: 0px; border-radius: 50px;border-color: #FDDE45;min-width: 5em;padding: 5px; }")
        self.btn_info.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_info.setIcon(icon3)
        self.btn_info.setIconSize(QtCore.QSize(75, 75))
        self.btn_info.setAutoDefault(False)
        self.btn_info.setFlat(False)
        self.btn_info.setObjectName("btn_info")
        self.verticalLayout_8.addWidget(self.btn_info)
        self.lbl_info = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_info.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info.setFont(font)
        self.lbl_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_info.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_info.setObjectName("lbl_info")
        self.verticalLayout_8.addWidget(self.lbl_info)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.btn_return = QtWidgets.QPushButton(settingForm)
        self.btn_return.setGeometry(QtCore.QRect(10, 10, 100, 50))
        self.btn_return.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_return.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_return.setFont(font)
        self.btn_return.setStyleSheet("QPushButton{\n"
"    color: #FDDE45;\n"
"    background-color: #FDDE45;\n"
"    border: 2px solid #A6A7A9;\n"
"    border-radius: 20px;\n"
"}")
        self.btn_return.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_return.setIcon(icon4)
        self.btn_return.setIconSize(QtCore.QSize(32, 32))
        self.btn_return.setObjectName("btn_return")

        self.retranslateUi(settingForm)
        self.btn_info.clicked.connect(settingForm.evt_info)
        self.btn_language.clicked.connect(settingForm.evt_language)
        self.btn_battery.clicked.connect(settingForm.evt_battery)
        self.btn_setting.clicked.connect(settingForm.evt_setting)
        self.btn_return.clicked.connect(settingForm.evt_return)
        QtCore.QMetaObject.connectSlotsByName(settingForm)

    def retranslateUi(self, settingForm):
        _translate = QtCore.QCoreApplication.translate
        settingForm.setWindowTitle(_translate("settingForm", "Form"))
        self.lbl_setting.setText(_translate("settingForm", "Setting"))
        self.lbl_language.setText(_translate("settingForm", "Language"))
        self.lbl_battery.setText(_translate("settingForm", "Battery"))
        self.lbl_info.setText(_translate("settingForm", "Info"))
import main_rc
