# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/root/ui/single_tray.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1280, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1280, 400))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #FFFFFF")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Korean, QtCore.QLocale.SouthKorea))
        MainWindow.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1280, 400))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(105, 380))
        self.label_4.setMaximumSize(QtCore.QSize(270, 400))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 10px;border-color: beige;min-width: 5em;padding: 5px; }\n"
"url(:/flag/korea_flag.png)")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/res/bumblebee_character_s.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setIndent(-1)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_fast = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_fast.sizePolicy().hasHeightForWidth())
        self.btn_fast.setSizePolicy(sizePolicy)
        self.btn_fast.setMinimumSize(QtCore.QSize(105, 0))
        self.btn_fast.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_fast.setFont(font)
        self.btn_fast.setStyleSheet("QRadioButton {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 15px;border-color: beige;min-width: 5em;padding: 5px; }\n"
"QRadioButton:hover{background-color:#FC6835;}\n"
"QRadioButton::indicator { width: 0px; height: 0px;}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/fast_icon_s.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_fast.setIcon(icon)
        self.btn_fast.setIconSize(QtCore.QSize(100, 80))
        self.btn_fast.setObjectName("btn_fast")
        self.verticalLayout_2.addWidget(self.btn_fast)
        self.btn_normal = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_normal.sizePolicy().hasHeightForWidth())
        self.btn_normal.setSizePolicy(sizePolicy)
        self.btn_normal.setMinimumSize(QtCore.QSize(105, 0))
        self.btn_normal.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_normal.setFont(font)
        self.btn_normal.setStyleSheet("QRadioButton {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 15px;border-color: beige;min-width: 5em;padding: 5px; }\n"
"QRadioButton:hover{background-color:#FC6835;}\n"
"QRadioButton::indicator { width: 0px; height: 0px;}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/normal_icon_s.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_normal.setIcon(icon1)
        self.btn_normal.setIconSize(QtCore.QSize(80, 80))
        self.btn_normal.setChecked(True)
        self.btn_normal.setObjectName("btn_normal")
        self.verticalLayout_2.addWidget(self.btn_normal)
        self.btn_slow = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_slow.sizePolicy().hasHeightForWidth())
        self.btn_slow.setSizePolicy(sizePolicy)
        self.btn_slow.setMinimumSize(QtCore.QSize(105, 0))
        self.btn_slow.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_slow.setFont(font)
        self.btn_slow.setMouseTracking(True)
        self.btn_slow.setStyleSheet("QRadioButton {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 15px;border-color: beige;min-width: 5em;padding: 5px; }\n"
"QRadioButton:hover{background-color:#FC6835;}\n"
"QRadioButton::indicator { width: 0px; height: 0px;}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/slow_icon_s.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_slow.setIcon(icon2)
        self.btn_slow.setIconSize(QtCore.QSize(100, 80))
        self.btn_slow.setCheckable(True)
        self.btn_slow.setAutoExclusive(True)
        self.btn_slow.setObjectName("btn_slow")
        self.verticalLayout_2.addWidget(self.btn_slow)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(54, 0))
        self.label_3.setMaximumSize(QtCore.QSize(300, 400))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        self.label_3.setFont(font)
        self.label_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_3.setStyleSheet("QLabel {background-color: #FDDE45;border-style: outset; border-width: 5px; border-radius: 10px;border-color: beige;min-width: 2em;padding: 5px; }")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/res/tray_single.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinbox1 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinbox1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox1.sizePolicy().hasHeightForWidth())
        self.spinbox1.setSizePolicy(sizePolicy)
        self.spinbox1.setMinimumSize(QtCore.QSize(172, 390))
        self.spinbox1.setMaximumSize(QtCore.QSize(400, 390))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.spinbox1.setFont(font)
        self.spinbox1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinbox1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinbox1.setStyleSheet("QSpinBox::up-button { width: 80px;color:#373535;} \n"
"QSpinBox::down-button { width: 80px;color:#373535;}\n"
"QSpinBox {background-color: #FDDE45;border-style: none; border-width: 1px; border-radius: 10px;border-color: #373535;min-width: 10em;padding: 1px;color:#373535; }")
        self.spinbox1.setWrapping(True)
        self.spinbox1.setFrame(True)
        self.spinbox1.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox1.setReadOnly(False)
        self.spinbox1.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinbox1.setAccelerated(True)
        self.spinbox1.setKeyboardTracking(True)
        self.spinbox1.setMaximum(10)
        self.spinbox1.setObjectName("spinbox1")
        self.horizontalLayout_6.addWidget(self.spinbox1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(105, 380))
        self.pushButton.setMaximumSize(QtCore.QSize(270, 400))
        self.pushButton.setBaseSize(QtCore.QSize(270, 390))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK KR")
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: #FDDE45;\n"
"border-style: outset; \n"
"border-width: 5px; \n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"min-width: 5em;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover{background-color:#F0B93D;};\n"
"")
        self.pushButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/tray_icon_go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(350, 350))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.evt_send_message)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_fast.setText(_translate("MainWindow", "Fast"))
        self.btn_normal.setText(_translate("MainWindow", "Normal"))
        self.btn_slow.setText(_translate("MainWindow", "Slow"))
import main_rc
