scan_filter_chain:
# - name: AngularBoundsFilter1
#   type: laser_filters/LaserScanAngularBoundsFilterInPlace
#   params:
#     lower_angle: 0
#     upper_angle: 3

- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    filter_type: 0
    max_range: 2.0
    max_range_difference: 0.02
    filter_window: 4
# - name: AngularBoundsFilter2
#   type: laser_filters/LaserScanAngularBoundsFilterInPlace
#   params:
#     lower_angle: -0.51
#     upper_angle: 0.45