from enum import Enum

# 사용자 정의 알람코드
class AlarmCodeList(Enum):
    OK = 0
    WAITING_USER = 1
    WAITING_CROSS = 2 
    JOB_PAUSE = 3
    JOB_CANCEL = 4
    JOB_RESUME = 5
    JOB_COMPLETED = 6
    NOT_CONNECTED = 52000  # 디바이스 접속실패시
    DISPLAY_ERROR = 52998 #모니터 접속이 끊어졌을때
    ESTOP_ERROR = 54013 #ESTOP 센서가 감지되었을때
    
class ALM_Fatal(Enum):
    BATTERY_TOO_LOW_SHUTDOWN = "50401: battery too low and shutdown"
    BATTERY_TEMPERATURE_TOO_HIGH = "50402: temperature of battery is too high"
    TRAYDOOR_ERROR = "50000: DOOR sensor signals must be exclusive."

    RESOURCE_EXHAUSTION = "50001: resource exhaustion"
    SW_ERROR = "50002: sw error"
    MAP_PARSE_ERROR = "50100: map parse error"
    MAP_LOAD_ERROR = "50101: map load error"
    MAP_TOO_LARGE = "50102: map is too large"
    MAP_EMPTY = "50103: map is empty"
    MAP_META_ERROR = "50104: map meta error"
    MAP_RESOLUTION_ILLEGAL = "50105: map resolution is illegal"
    LOAD_MOBILEROBOTS_LIB_ERROR = "50200: load mobilerobots lib error"
    INIT_MOBILEROBOTS_FAILED = "50201: Failed to initialize mobilerobots"
    MOBILEROBOTS_REGISTER_ERROR = "50202: mobilerobots register error"
    UNSUPPORTED_ROBOT_MOTION_MODEL = "50203: unsupported robot motion model"
    MOBILEROBOTS_NOT_FOUND = "50204: can not find mobilerobots"
    HARDWARE_CONNECT_ERROR = "50300: hardware connect error"
    DSP_FIRMWARE_MODEL_NOT_FOUND = "50301: dsp firmware model can not get"
    FIRMWARE_VERSION_TOO_LOW = "50304: firmware version too low"
    FIRMWARE_MODEL_UNREACHABLE = "50305: firmware model unreachable or robot model param config error"
    GYRO_ORIGINAL_DATA_ERROR = "50400: gyro original data error"
    NVME_FULL = "50405: NVME FULL"
# Example usage
# if __name__ == "__main__":
#     for alarm in AlarmCode:
#         print(f"Alarm: {alarm.name}, Code and Message: {alarm.value}")
class ALM_User(Enum):
    USER_ESTOP = "54000: ESTOP By User"
    SAFETY_DOOR_LIFT = "54019: DoorClose required before lift up"
    TRAY360_SAFETY = "54007: Not enough space for tray rotate"
    OUT_OF_SERVING_RANGE = "54028: Not able to serve the distance"
    SAFETY_TRAYDOOR = "54006: Lift Down is required before DoorOpen"
    SAFETY_ARM = "54017: tray and lift must be on the origin before Arm control."
    SAFETY_MOTORH_ROTATEMAIN = "54018: All others must be on the origin before MotorH run."
    SAFETY_MOTORH_2 = "54014: Invalid Rotate Status, only 0 or 180 degree allowed"
    CMD_INTERVAL_DUPLICATED = "54023: MotorCmd duplicated."
    ABNORMAL_CMD_DATA = "54022: abnormal CMD data"
    TRAY_WEIGHT_LIMIT = "54021: Too much load in the tray"
    ROBOT_JUST_INITIALIZED = "52010: BLB is now just started."
    MOTOR_TORQUE_INVALID = "54027: Motor torque check error"    
    JOB_SUSPENDED = "54008: Job Suspended"
    JOB_PAUSED = "54010: Job Paused"
    JOB_CANCELED = "54011: Job Canceled"
    JOB_HOMECALL = "54004: Home Called"
    JOB_RESUMED = "54012: Job Resume"
    CMD_FORMAT_INVALID = "50106: Cmd format invalid"    
    CMD_ISNULL = "54070: No cmd found"

    BATTERY_ERROR = "54001: battery error"
    MOTOR_OVERSPEED = "54003: motor overspeed"
    
    #DRIVER_EMERGENCY_STOP = "54013: driver emergency stop"
    RS485_HARDWARE_ERROR = "54016: RS485 hardware error"
    REFLECTORS_MATCH_FAILED = "54020: reflectors match failed, please set right init pose"
    WHICH_DRIVER_EMERGENCY_STOP = "54025: which driver emergency stop"
    WHICH_DRIVER_ERROR_CODE = "54026: which driver have error code"
    CHECK_DI_FALSE = "54028: checkDi is false"
    SERIAL_PORT_USED_MULTIPLE_TIMES = "54031: devName of serial port is used more than 1 times"
    CANNOT_CONNECT_WITH_CAMERA = "54051: cannot connect with camera"
    DETECT_TWO_TAG_SAME_ID = "54052: detect two tag with same ID"
    TAG_CANNOT_BE_SEEN = "54053: Tag cannot be Seen, please enable PGV with Localization or adjustLocalization"
    BATTERY_REPORT_WARNING = "54065: battery report warning"
    MUSHINY_LED_TIMEOUT = "54066: mushiny led timeout"
    EXTERNAL_CONTROL_WARNING = "54067: external control warning"
    CLEAN_LASER_CONTAMINATION_ERROR = "54071: please clean laser, get Contamination Error with Nanosick"
    STEER_RANGE = "54080: Steer Range:"
    DSP_RECONFIGURING = "54100: DSP reconfiging"
    LOW_BATTERY = "54211: low battery"
    ROBOT_BLOCKED = "54231: Caution: robot is blocked"
    IGNORING_TASK_DISENSOR = "54232: Ignoring Task caused by DISensor"
    IMU_NOISE_TOO_LARGE = "54300: imu noise is too large"
    NEWSPEED_TIMEOUT_HANDLE_STATUS = "54302: newspeed timeout handle status"
    DOMOTOR_CALIBRATING = "54304: DOMotor is calibrating"
    RESET_MOTOR_STATE = "54305: reset motor should in state when all motors are stopped"
    REC_FAIL = "54901: rec fail"
    CANNOT_READ_PALLET_FILE = "54902: can not read pallet recognize file"
    CUSTOM_RECOGNIZE_FILE_ID_NULL = "54903: Custom Recognize File Txt ID is null, Please Check!"
    MULTI_PALLET_RECOGNITION_INCONSISTENT = "54904: Multi-pallet recognition method don't consistent"
    NO_GOODS_ON_PALLET = "54905: 3D measure result has shown there is no Goods on the pallet"
    GOODS_SIZE_THRESHOLD = "54906: goods size threshold"
    ROUTE_PROTOCOL_VERSION_MODIFIED = "55000: 'RouteProtocolVersion' is modified to: XXX, but current is: XXX, and it takes effect after reboot."
    ROBOT_IN_DISPATCHING_STATE = "55001: The robot is in the dispatching state. If you need to control, please regain control and go offline during dispatching."
    RBK_PALLET_NOT_ACTIVATED = "55502: rbk_pallet is not activated"
    RBK_PGV_LOC_NOT_ACTIVATED = "55503: rbk_pgv_loc is not activated"
    RBK_TAG_NAV_NOT_ACTIVATED = "55504: rbk_tag_nav is not activated"
    RBK_SPIN_NOT_ACTIVATED = "55506: rbk_spin is not activated"
    RBK_REFLECTOR_NOT_ACTIVATED = "55507: rbk_reflector is not activated"
    RBK_3DCAMERA_NOT_ACTIVATED = "55508: rbk_3dcamera is not activated"
    RBK_DYNAMIC_NAV_NOT_ACTIVATED = "55509: rbk_dynamic_nav is not activated"
    RBK_ROAMING_NOT_ACTIVATED = "55510: rbk_roaming is not activated"
    RBK_SCRIPT_NOT_ACTIVATED = "55511: rbk_script is not activated"
    IMU_NOT_CALIBRATED = "55600: IMU has NOT been calibrated while the skid detection is enabled"
    ODOMETER_UNRELIABLE = "55601: Odometer being unreliable because of wheel movements inconsistency"
    IO_WRITE_SPEED_HIGH = "55710: IO write speed higher than normal"
    GYRO_FLYING_AFTER_CALIBRATION = "57009: The gyro is flying in the 2 second after calibration. Integration"

# # Example usage
# if __name__ == "__main__":
#     for alarm in UserAlarm:
#         print(f"Alarm: {alarm.name}, Code and Message: {alarm.value}")

class ALM_error(Enum):
    ARM_BALANCING_ERROR = "52039: Balancing Control Arm1 between Arm2 is Failed. Stopped emergency."
    MOTOR_CALIBRATE_REQUIRED = "52956: Some MOTORs are not CALIBRATED. Do CALIBRATE First." #모터 캘리브레이션 정보가 없을때
    MOTOR_COMM_ERROR = f"{AlarmCodeList.NOT_CONNECTED.value}: Not able to connect some motors" #모터 modbus 접속 실패
    INIT_MOBILEROBOTS_FAILED = "52001: Failed to initialize some MOTORS" #일부 모터 초기화 실패.
    VOLTAGE_WARN_LOW = "52124: Battery under voltage seriously"
    VOLTAGE_INFO_FULL = "52125: Battery fully charged."
    BATTERY_TIMEOUT_ERROR = "52960: BMS Info timeout error"
    RFID_READER_ERROR = "52113: RFID reader error"
    ROBOT_OUT_OF_PATH = "52201: robot out of path"
    DEADEND_DETECTED = "52950: Rail deadend detected"

    # BATTERY_TOO_LOW_TO_MOVE = "52503: battery is too low to move"
    # BATTERY_CONNECT_ERROR = "52400: battery connect error during charging"
    
    SRC800_ACTIVATION_PROBLEM = "52002: src800 activation has problem"
    STEER_OFFSET_FILE_NOT_EXIST = "52003: steerOffsetFile's path doesn't exist!"
    SAME_ID_IN_MAP = "52015: stations with the same id number in the map, points with the same id number in the map"
    LESS_THAN_3_REFLECTORS = "52019: Detect less than 3 reflectors"
    RBK_LASER_LOC_NOT_ACTIVATED = "52020: rbk_laser_loc is not activated, please activate it"
    ROLLER_ERROR = "52030: roller error"
    DISCONNECTED_COMPONENT = "52031: roller or jack or hook disconnected?"
    MODBUS_JACK_ERROR = "52034: ModbusJack error or ModbusTractor error"
    ARM_DISCONNECTED = "52050: arm disconnected"
    ARM_GRASP_LOAD = "52051: Arm GraspLoad to/from target"
    INTERNAL_LASER_ERROR = "52096: internal laser error"
    RESTART_LASER = "52097: please restart laser, get internal Error with Nanosick"
    CANNOT_CONNECT_SICK_NANO_LASER = "52098: cannot connect sick nano laser with same port"
    LASER_CONFIG_PARAM_ERROR = "52099: laser config param error"
    CANNOT_CONNECT_LASER = "52100: can't connect with laser"
    LASER_DATA_INVALID = "52101: laser data invalid"
    LOCALIZATION_CANNOT_GET_LASER_DATA = "52102: localization module cannot get laser data"
    CANNOT_RECEIVE_LASER_DATA_UDP = "52103: cannot receive laser data from udp"
    SET_FRONT_LASER_FOR_LOCALIZATION = "52104: please set front laser as use for localization"
    SET_BACK_LASER_FOR_LOCALIZATION = "52105: please set back laser as use for localization"
    ODO_DATA_LOST = "52106: odo data lost"
    SWITCH_MAP_ERROR = "52107: Switch map error in current station point"
    TIME_SYNCHRONIZATION_ERROR = "52108: time synchronization error"
    REFERENCE_AREA_BLOCKED = "52109: ReferenceArea is blocked"
    GYRO_NO_DATA = "52110: Error in Gyro. No data received. Gyro. cpp doRun()"
    MOTOR_DRIVER_CONNECTION_ERROR = "52111: motor driver connection error"
    ULTRASONIC_ERROR = "52112: ultrasonic error"
    MAGNETIC_TRACKER_0_ERROR = "52114: magnetic 0 tracker error"
    MAGNETIC_TRACKER_1_ERROR = "52115: magnetic 1 tracker error"
    CONTROLLER_NET_DOWN = "52116: controller net down"
    DIOBOARD_NET_DOWN = "52117: dioboard net down"
    SEER_DIO_HEARTBEAT_LOSS = "52118: seer dio heart beat loss"
    LOW_TASK_FREQUENCY = "52119: low task frequency"
    UNRELEASED_DO = "52120: Don't set DO when movetask unreleased DO"
    ROBOT_FALL_DOWN = "52122: robot fall down"
    DSP_CHASSIS_MODBUS_IO_ERROR = "52123: DSPChassis modbus IO error"
    PGV_CONNECTION_ERROR = "52127: PGV connection error"
    PGV_INFO_MISMATCHED_DEVICE_ID = "52128: PGV info with mismatched device id"
    WEIGHING_DEVICE_TIMEOUT = "52129: Weighing device connect timeout"
    MOTOR_GVDD_OVER_VOLTAGE = "52130: motor GVDD over voltage"
    MOTOR_FET_OVER_CURRENT = "52131: motor FET over current"
    MOTOR_OVER_TEMPERATURE = "52132: motor over temperature"
    MOTOR_VDD_UNDER_VOLTAGE = "52133: motor VDD under voltage"
    MOTOR_SECOND_ERROR = "52134: motor second error"
    MOTOR_ERROR_SEE_LOG = "52135: motor error see log"
    CHASSIS_NEW_SPEED_TIMEOUT = "52136: chassis new speed timeout"
    STEER_ANGLE_OVERFLOW = "52137: steer angle overflow"
    FORK_ENCODER_CONNECTION_ERROR = "52138: fork encoder connection error"
    STEER_WHEELBASE_TOO_SMALL = "52139: steer wheelbase is too small"
    LIFT_SAFE_CONTROL_TRIGGER = "52145: lift safe control trigger"
    DSP_CHASSIS_MODEL_CONFIG_ERROR = "52155: DSPChassis model config error"
    WALKING_JACK_MOTOR_INTERLOCK = "52156: walking jack motor interlock"
    ILLEGAL_SPEED = "52160: robot received an illegal speed"
    DESTINATION_HAS_GOODS = "52161: Unload, but the destination has goods! Or The Goal has goods. Cannot unLoad!!!"
    CONTACT_DI_NO_GOODS = "52162: ContactDi doesn't detect Goods! Or Fork Goods Missing. Cannot Detect Goods in the"
    VELOCITY_ERROR = "52163: Error in Velocity or Error in Velocity Decomposition"
    FORK_CANNOT_LOAD_AGAIN = "52164: Fork Cannot Load Again. ContactDi is True"
    FORK_OVERTIME = "52165: Fork is over time"
    DI_AWAY_GOAL_DIST = "52166: DI TRUE BUT AWAY GOAL DIST or ReachDI is true but AGV is not in the goal."
    REACH_GOAL_NO_DI = "52167: REACH GOAL LOAD NO DI or AGV is in the goal but reachDI is false."
    CONTACT_DI_NO_GOODS_AGAIN = "52168: ContactDi doesn't detect Goods!"
    NOT_ENOUGH_3D_POINTCLOUD = "52169: No enough 3D pointCloud in current map, please check or not use 3DLocalization with Current Laser"
    MODEL_CONFIG_ERROR = "52195: model config error"
    ROBOT_BLOCKED = "52200: robot is blocked"
    CHARGE_PROBLEM = "52202: is one of the following - can not open Recfile. - charge failed. Out of time: - openCharge is set. Out of waiting time: - charge timeout: - charge timeout: in rec stage. - can not open Recfile. - Read Charger in robot. model file"
    CHARGE_DEVICE_NOT_ENABLED = "52203: Charge device is not enabled!"
    CHARGER_SPOT_STATUS_ERROR = "52204: chargerspot status error"
    CAMERA_DISCONNECTED = "52250: 3D camera disconnected"
    CANNOT_RECEIVE_IFM_DATA = "52251: cannot receive IFM data"
    CANNOT_CONNECT_LOCCAMERA = "52253: cannot connect with locCamera"
    LOW_LOCALIZATION_CONFIDENCE = "52300: too low confidence of localization"
    CANNOT_DETECT_TAG = "52301: Cannot detect tag after some distance"
    CANNOT_NAVIGATE_BEFORE_CONFIRM = "52302: Cannot navigate before confirming localization"
    HOOK_ERROR_AGAIN = "52309: hook has an error"
    DISPATCH_DISCONNECT = "52500: disconnect from dispatching system"
    BUTTON_TIMEOUT = "52501: button timeout"
    DISPATCH_COMMAND_ERROR = "52502: Dispatching system command error"
    LOW_REACH_ACCURACY = "52600: low reach accuracy"
    CANNOT_FIND_FEASIBLE_PATH = "52700: cannot find a feasible path"
    CANNOT_FIND_TARGET_ID = "52701: cannot find target id"
    PATH_PLAN_FAILED = "52702: path plan failed"
    UNSUPPORTED_NAVIGATION_METHOD = "52703: unsupported navigation method"
    CHARGE_FAILED_NO_PREPOINT = "52704: charge failed but not set pre-point"
    MOTION_PLANNING_FAILED = "52705: motion planning failed"
    CANNOT_FIND_MAGSTRIPE = "52706: cannot find magstripe"
    DESTINATION_HAS_OBSTACLES = "52708: destination has obstacles"
    CANNOT_FIND_PATROL_ROUTE = "52710: cannot find patrol route"
    DO_DI_AREA_OVERLAP = "52713: DO or DI area overlap?"
    GO_INTO_SHELF_FAILED = "52714: go into shelf failed"
    CURRENT_POS_HAS_OBSTACLES = "52715: current pos has obstacles"
    CHARGER_HARDWARE_PROBLEM = "52716: charger hardware problem"
    CHARGER_TCP_CONNECTION_PROBLEM = "52717: charger tcp connection problem"
    DETECT_SKID_AND_STOP = "52718: Detect Skid and stop"
    GNSS_SERIAL_PROBLEM = "52730: gnss serial problem!"
    RTK_BASE_SERIAL_PROBLEM = "52731: RTK Base serial problem!"
    JACK_FORK_CONFIG_ERROR = "52800: jack or fork config error?"
    MODULE_MOTOR_CONTROL_ERROR = "52801: module or motor control error?"
    UPLIMIT_DOWNLIMIT_ERROR = "52802: upLimit or downLimit error?"
    THIRD_PARTY_ERROR = "52900: third-party error: XXXXX"
    SHELF_ALREADY_EXISTS = "52951: a shelf already there"
    JACK_PGV_ADJUST_CONFIG_ERROR = "52952: jack, rec, pgv adjust config file error"
    MOTOR_FOLLOWING_ERROR = "52953: motor following error"
    MOTOR_CALIBRATE_TIMEOUT = "52954: motor calibrate timeout"
    SRC_CANNOT_SWITCH_MODE = "52955: src cannot switch mode while moving"
    DOMOTOR_CALIBRATE_TIMEOUT = "52957: DOMotor calibrate timeout"
    DOMOTOR_LIMIT_DI_TRIGGERED = "52958: DOMotor limit DI triggered"
    DISTANCESENSOR_CONNECT_TIMEOUT = "52959: distanceSensor connect timeout"
    REC_FAIL_MAX_TIMES = "52961: rec fail reach max times"
    SPIN_MOTOR_BLOCK_DI_TRIGGERED = "52962: Spin motor's block di triggered in calibrating"
    PALLET_TAG_OUT_OF_POSITION = "52963: The pallet or tag is out of the right position."
    FOLLOWING_ERROR_MOTORS = "52997: Following error motors: [motor a], [motor B], ..."
    DISPLAY_SPECIFIC_CONTENT_1 = f"{AlarmCodeList.DISPLAY_ERROR.value}: display specific content according to actual situation"
    DISPLAY_SPECIFIC_CONTENT_2 = "52999: display specific content according to actual situation"
    CUSTOM_IN_SCRIPT = "53000: custom in script"
    MINSIGNAL_LEVEL_AVAILABLE_LOW = "53100: MinSignalLevelAvailable is smaller than MinSignalLevelKeep"
    LINEAR_MOTOR_FOLLOWING_ERROR = "53101: Linear motor following error"
    IMU_POSE_NON_UNIT = "53102: quaternion of IMU pose is non-unit, please recalibrate the IMU"
    CONTROLLER_VOLTAGE_LOW = "53103: controller voltage lower than the controller rated voltage"
    SCANNER_DEVNAME_NOT_EXIST = "53104: Scanner devName is not exist"
    MOTOR_INITIALIZE_TIMEOUT = "53105: motor initialize timeout"

# # Example usage
# if __name__ == "__main__":
#     for error in RobotErrorCode:
#         print(f"Error: {error.name}, Code and Message: {error.value}")
